.github/pylintrc, .github/workflows/pylint.yaml, .gitignore, common/python/cctrusted_base/binaryblob.py, common/python/cctrusted_base/imr.py, common/python/cctrusted_base/utility.py, samples/CCTrustedInspect/README.md, setupenv.sh, vmsdk/python/cc_imr_cli.py, vmsdk/python/cctrusted/__init__.py, vmsdk/python/cctrusted/api.py, vmsdk/python/cctrusted/cc_linux.py
1. add github action for pylint
2. add api class for python vmsdk
3. add binaryblob, imr, utility for common sdk
=> vmsdk: initiate the code structure

README.md
This PR is to fix the typos and gramatical errors to make it more readable.
=> README.md: Fix grammatical errors and typos

common/python/cctrusted_base/tcg.py
Add class 'TcgEventType', 'TcgImrEventLogEntry', 'TcgEfiSpecIdEvent' and 'TcgEfiSpecIdEventAlgorithmSize' for event log parsing
=> common: Add more TCG classes for event log parsing

vmsdk/python/cctrusted/cvm.py
Signed-off-by: Hairong Chen hairong.chen@intel.com
=> cvm.py: bug fix for CCA type

common/python/cctrusted_base/quote.py, common/python/cctrusted_base/tdx/qh.py, vmsdk/python/cc_quote_cli.py, vmsdk/python/cctrusted/api.py, vmsdk/python/cctrusted/cvm.py
This is the initial version that includes:
1. Add some scaffolding data structures and helper functions.
2. Get TD Quote raw data (and dump to stdout) using ioctl TDVMCALL.
=> vmsdk: add get_quote (python)

common/python/cctrusted_base/ccel.py, common/python/cctrusted_base/eventlog.py, common/python/cctrusted_base/imr.py, common/python/cctrusted_base/tcg.py, vmsdk/python/cc_event_log_cli.py, vmsdk/python/cctrusted/api.py, vmsdk/python/cctrusted/cvm.py
* add CCEL class
* refine TCG related classes
* add implementation of event log processing for tdx
* add api for get_eventlog()
* fix minor typo
=> vmsdk: get_eventlog initial commit

common/python/cctrusted_base/eventlog.py, common/python/cctrusted_base/tcg.py, vmsdk/python/cc_event_log_cli.py, vmsdk/python/cctrusted/cvm.py, vmsdk/python/cctrusted/sdk.py
* enhance comments
* enhance dump function
* remove ccel_data attr in cvm class
=> vmsdk: enhance event log implementation

common/python/cctrusted_base/tdx/quote.py
Format reference: "A.3.10. Enclave Report Body" in https://download.01.org/intel-sgx/latest/dcap-latest/linux/docs/Intel_TDX_DCAP_Quoting_Library_API.pdf
=> vmsdk (python): parse Enclave Report Body

common/python/cctrusted_base/eventlog.py, common/python/cctrusted_base/tcg.py, vmsdk/python/cctrusted_vm/cvm.py, vmsdk/python/cctrusted_vm/sdk.py
* add IMA event log fetching
* declare new class for event log formatting
=> vmsdk: add runtime event log fetching

common/python/cctrusted_base/eventlog.py
* enhance ima event log parsing logic
* fix description of Eventlog attribute
=> vmsdk: enhance ima event log parsing

common/python/cctrusted_base/eventlog.py, common/python/cctrusted_base/tcg.py
* update event type to latest
* add parsing for specific event types
* fix minor error in event formatting
=> vmsdk: add further parsing for event data

common/python/cctrusted_base/eventlog.py
* skip all EV_NO_ACTION event in event log replay
* enhance event log select logic by using the index start from 0
=> vmsdk: fix event log replay logic on EV_NO_ACTION

common/python/cctrusted_base/api.py
* change the get_eventlog() API with return as Eventlogs
* add new replay_eventlog() API
=> vmsdk: change definitions in api

common/python/cctrusted_base/tdx/quote.py
Remove the unncessary parameter from its constructor.
=> common/python: refine constructor for TdxQuote

README.md, docs/API-usage-example.md, vmsdk/python/cc_event_log_cli.py
* change cli logic according to get_cc_eventlog() output change
* edit docs describing get_cc_eventlog() usage
=> vmsdk: fix eventlog cli

common/rust/cctrusted_base/src/tdx/common.rs, vmsdk/rust/cctrusted_vm/src/tdvm.rs
this commit adds support for container mounted CCEL and IMA file path
Signed-off-by: Hairong Chen hairong.chen@intel.com
=> VMSDK/rust: add support for container mounted file path

README.md, docs/API-usage-example.md
Replace old links with new ones for CCNP.
=> README.md: fix links to CCNP

common/python/cctrusted_base/eventlog.py, common/python/cctrusted_base/tcgcel.py
* add event log classes for Canonical event logs
* refine replay func to replay Canonical Event logs
=> [WAIT FOR REVIEW] common: add Canonical Event log classes and replay method

common/golang/cctrusted_base/tdx/tdx.go
* add path for TDX attest config
* fetch attest configs at init
=> common: add tdx attest config for vsock support in golang

docs/API-usage-example.md, docs/vmsdk-eventlog-sample-output-with-IMA.txt
1. Add full output event log example file
2. Update links in document
=> Add node level event log example output file

common/golang/cctrusted_base/api.go, common/golang/cctrusted_base/model.go
* add tsm support in CcReport definition
=> common: extend type CcReport in golang impl
